# Generated by Django 5.2.12 on 2026-03-25 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Mockup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[('tshirt', 'Camiseta'), ('mug', 'Taza'), ('cap', 'Gorra'), ('tote', 'Tote Bag'), ('pen', 'Bolígrafo'), ('notebook', 'Libreta'), ('hoodie', 'Sudadera'), ('usb', 'USB')], max_length=20)),
                ('color_producto', models.CharField(default='#1a1a1a', max_length=7)),
                ('logo_escala', models.FloatField(default=1.0)),
                ('logo_opacidad', models.FloatField(default=1.0)),
                ('imagen_generada', models.ImageField(blank=True, null=True, upload_to='mockups/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mockups', to='api.cliente')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
