import { Project, Bid } from "./types";

export const MOCK_BIDS: Record<string, Bid[]> = {
  "1": [
    {
      id: "b1",
      project_id: "1",
      company_name: "SubliPrint MX",
      contact_email: "ventas@subliprint.mx",
      amount: 10800,
      delivery_days: 10,
      notes: "Contamos con 5 años de experiencia en sublimación corporativa. Incluimos prueba de color sin costo y entrega en sus instalaciones.",
      created_at: "2026-03-21T10:00:00Z",
    },
    {
      id: "b2",
      project_id: "1",
      company_name: "Estampados del Norte",
      contact_email: "info@estampadosnorte.com",
      amount: 11500,
      delivery_days: 7,
      notes: "Entrega express en 7 días. Maquinaria de última generación, colores vibrantes garantizados. Muestra física incluida.",
      created_at: "2026-03-22T14:00:00Z",
    },
    {
      id: "b3",
      project_id: "1",
      company_name: "ColorMax Studio",
      contact_email: "hola@colormax.studio",
      amount: 9900,
      delivery_days: 14,
      notes: "Precio más competitivo del mercado. Garantía de calidad o reimpresión sin costo.",
      created_at: "2026-03-23T09:00:00Z",
    },
  ],
  "2": [
    {
      id: "b4",
      project_id: "2",
      company_name: "Rótulos Express",
      contact_email: "ventas@rotulosexp.mx",
      amount: 16200,
      delivery_days: 12,
      notes: "Especialistas en flotillas corporativas. Instalación con garantía de 2 años sobre el vinilo. Presupuesto detallado por unidad disponible.",
      created_at: "2026-03-20T11:00:00Z",
    },
    {
      id: "b5",
      project_id: "2",
      company_name: "Vinyltech",
      contact_email: "contacto@vinyltech.com.mx",
      amount: 17800,
      delivery_days: 8,
      notes: "Vinilo 3M de primera calidad, garantía de 5 años exterior. Instaladores certificados en CDMX y área metropolitana.",
      created_at: "2026-03-21T16:00:00Z",
    },
  ],
  "3": [
    {
      id: "b6",
      project_id: "3",
      company_name: "Promo Total",
      contact_email: "ventas@promototal.mx",
      amount: 41000,
      delivery_days: 20,
      notes: "Somos proveedores de artículos promocionales con catálogo completo. Podemos ajustar materiales según presupuesto. Muestra de cada artículo sin costo.",
      created_at: "2026-03-19T12:00:00Z",
    },
  ],
  "5": [
    {
      id: "b7",
      project_id: "5",
      company_name: "Letreros Polanco",
      contact_email: "info@letrerospolanco.mx",
      amount: 3200,
      delivery_days: 3,
      notes: "Especialistas en zona Polanco. Instalación al día siguiente de aprobación. Garantía de permanencia 3 años.",
      created_at: "2026-03-17T10:00:00Z",
    },
    {
      id: "b8",
      project_id: "5",
      company_name: "Vinilo y Más",
      contact_email: "hola@viniloymes.com",
      amount: 2800,
      delivery_days: 5,
      notes: "Precio más bajo con calidad garantizada. Materiales importados de Europa.",
      created_at: "2026-03-17T15:00:00Z",
    },
    {
      id: "b9",
      project_id: "5",
      company_name: "Gráficos Urbanos",
      contact_email: "ventas@graficosurbanos.mx",
      amount: 3500,
      delivery_days: 2,
      notes: "Entrega en 48hrs. Incluye diseño de arte si es necesario ajustar el logo.",
      created_at: "2026-03-18T09:00:00Z",
    },
    {
      id: "b10",
      project_id: "5",
      company_name: "Señalética Pro",
      contact_email: "info@senaleticapro.com",
      amount: 3100,
      delivery_days: 4,
      notes: "Más de 10 años en el mercado. Trabajo garantizado o devolvemos el dinero.",
      created_at: "2026-03-18T14:00:00Z",
    },
  ],
  "6": [
    {
      id: "b11",
      project_id: "6",
      company_name: "Gorras y Más",
      contact_email: "ventas@gorrasymas.mx",
      amount: 8200,
      delivery_days: 15,
      notes: "Especialistas en gorras bordadas para equipos deportivos. Muestra sin costo.",
      created_at: "2026-03-11T10:00:00Z",
    },
    {
      id: "b12",
      project_id: "6",
      company_name: "BordadosPro",
      contact_email: "info@bordadospro.com",
      amount: 7600,
      delivery_days: 18,
      notes: "Precio más bajo. Bordado de alta definición con máquinas Brother industriales.",
      created_at: "2026-03-12T14:00:00Z",
    },
  ],
};

export const MOCK_PROJECTS: Project[] = [
  {
    id: "1",
    title: "200 playeras sublimadas para evento corporativo",
    category: "sublimation",
    description: "Necesitamos 200 playeras sublimadas para el evento anual de nuestra empresa. El diseño ya está listo en formato vectorial. Tallas variadas del S al XL.",
    requirements: "Talla S: 40 pzas, M: 60 pzas, L: 60 pzas, XL: 40 pzas. Material poliéster 100%. Colores completos en frente y espalda. Archivo en AI o PDF.",
    budget: 12000,
    deadline: "2026-04-15",
    contact_name: "Mariana Torres",
    contact_email: "mariana@empresa.com",
    status: "open",
    created_at: "2026-03-20T10:00:00Z",
    bids: MOCK_BIDS["1"],
  },
  {
    id: "2",
    title: "Rotulación de flotilla de 5 camionetas",
    category: "vinyl",
    description: "Rotulación completa para 5 camionetas de reparto. Incluye logos laterales, datos de contacto y gráficos decorativos en vinilo de alta duración.",
    requirements: "Vinilo de corte para logos. Impresión digital para degradados. Laminado brillante. Instalación incluida en CDMX.",
    budget: 18500,
    deadline: "2026-04-30",
    contact_name: "Roberto Salinas",
    contact_email: "roberto@distribuidora.mx",
    status: "open",
    created_at: "2026-03-19T14:30:00Z",
    bids: MOCK_BIDS["2"],
  },
  {
    id: "3",
    title: "Kit de bienvenida para 150 empleados nuevos",
    category: "merchandise",
    description: "Necesitamos kits de bienvenida para nuevos empleados: mochila, libreta, pluma, taza y playera con el logo de la empresa.",
    requirements: "Mochilas negras con bordado. Libretas A5. Tazas de 11oz con sublimación. Plumas metálicas grabadas. Playeras algodón con serigrafía.",
    budget: 45000,
    deadline: "2026-05-01",
    contact_name: "Sofía Mendoza",
    contact_email: "sofia.mendoza@corp.com",
    status: "open",
    created_at: "2026-03-18T09:15:00Z",
    bids: MOCK_BIDS["3"],
  },
  {
    id: "4",
    title: "Banners y lonas para stand de exposición",
    category: "sublimation",
    description: "Producción de material gráfico para stand en expo de tecnología: 2 banners retráctiles, 1 lona de fondo 3x2m y 4 banners de pie.",
    requirements: "Impresión en lona 440g. Acabados con ojillos. Monturas incluidas para banners retráctiles.",
    budget: 8500,
    deadline: "2026-04-10",
    contact_name: "Diego Ramírez",
    contact_email: "diego@techstartup.io",
    status: "open",
    created_at: "2026-03-17T16:45:00Z",
    bids: [],
  },
  {
    id: "5",
    title: "Letras de vinilo para local comercial",
    category: "vinyl",
    description: "Instalación de nombre del negocio en fachada con letras de vinilo, horario de atención y logo en vitrina interior.",
    requirements: "Letras de 15cm de alto en vinilo negro mate. Logo a color en vinil impreso. Horario en blanco. Local en Polanco, CDMX.",
    budget: null,
    deadline: null,
    contact_name: "Valentina Cruz",
    contact_email: "vale@mitienda.com",
    status: "open",
    created_at: "2026-03-16T11:00:00Z",
    bids: MOCK_BIDS["5"],
  },
  {
    id: "6",
    title: "Gorras bordadas para equipo de fútbol",
    category: "merchandise",
    description: "100 gorras con bordado del escudo del equipo para temporada 2026. Colores del equipo: azul marino y dorado.",
    requirements: "Gorras de 6 paneles. Bordado de alta definición en frente. Talla única con ajuste trasero.",
    budget: 9000,
    deadline: "2026-04-20",
    contact_name: "Carlos Vega",
    contact_email: "carlos@clubdeportivo.mx",
    status: "closed",
    created_at: "2026-03-10T08:00:00Z",
    bids: MOCK_BIDS["6"],
  },
];
