# Generated by Django 5.2.12 on 2026-03-27 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company_type', models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('merchandising', 'Merchandising'), ('printing', 'Printing')], max_length=20)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, help_text='Specific technical requirements or specs')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('awarded', 'Awarded')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awarded_to', models.ForeignKey(blank=True, limit_choices_to={'company_type': 'vendor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_jobs', to='marketplace.company')),
                ('client', models.ForeignKey(limit_choices_to={'company_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to='marketplace.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(help_text='Describe your approach, timeline, and qualifications')),
                ('delivery_days', models.PositiveIntegerField(help_text='Estimated delivery in business days')),
                ('is_awarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(limit_choices_to={'company_type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_bids', to='marketplace.company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='marketplace.job')),
            ],
            options={
                'ordering': ['amount'],
                'unique_together': {('job', 'vendor')},
            },
        ),
    ]
